fossee_theme.settings:
  type: theme_settings
  label: 'FOSSEE theme settings'
  mapping:
    primary_color:
      type: string
      label: 'Primary color'
    hero_slider_images:
      type: sequence
      label: 'Hero slider images'
      sequence:
        type: integer
        label: 'File ID'
    footer_text:
      type: text
      label: 'Footer text'
    show_social_links:
      type: boolean
      label: 'Show social media links'
    iitb_logo:
      type: integer
      label: 'IITB logo'
    fossee_logo:
      type: integer
      label: 'FOSSEE logo'
    facebook_url:
      type: string
      label: 'Facebook URL'
    youtube_url:
      type: string
      label: 'YouTube URL'
    linkedin_url:
      type: string
      label: 'LinkedIn URL'
    instagram_url:
      type: string
      label: 'Instagram URL'